pipeline {
  agent none
  environment {
    LC_ALL = 'C.UTF-8'
  }
  stages {
    stage('build') {
      parallel {
        stage('amd64') {
          agent {
            docker {
              image 'modelicastandardlibrary/build-deps:amd64-20190513'
              label 'linux'
              alwaysPull true
            }
          }
          environment {
            LIBDIR = "linux64"
          }
          steps {
            sh 'hostname'
            allAutotools()
          }
        }
        stage('i386') {
          agent {
            docker {
              image 'modelicastandardlibrary/build-deps:i386-20190513'
              label 'linux'
              alwaysPull true
            }
          }
          environment {
            LIBDIR = "linux32"
          }
          steps {
            sh 'hostname'
            allAutotools()
          }
        }
      }
    }
  }
}

def allAutotools() {
  for (String CC in ["gcc-4.8", "gcc-5", "gcc-6", "gcc-7", "gcc-8", "clang-3.9", "clang-4.0", "clang-5.0", "clang-6.0", "clang-7"]) {
    autotools(CC, CPPFLAGS)
  }
  for (String CPPFLAGS in ["-DNO_FILE_SYSTEM", "-DTABLE_SHARE", "-DNO_LOCALE", "-DNO_MUTEX"]) {
    autotools("gcc-8", CPPFLAGS)
  }
}

def autotools(CC, CPPFLAGS) {
  sh """
  export CC=$CC
  export CPPFLAGS=$CPPFLAGS
  export CFLAGS=-Os
  rm -rf Modelica/Resources/Library/*
  mkdir -p Modelica/Resources/Library/\$LIBDIR
  cd Modelica/Resources/BuildProjects/autotools
  git clean -fdx .
  ./autogen.sh
  ./configure --libdir="\$PWD/../../Library/\$LIBDIR" --enable-static --enable-shared
  make --output-sync -j4
  make install
  """
  sh """
  cd Modelica/Resources/Test
  ./test.sh
  """
}
