pipeline {
  agent none
  environment {
    LC_ALL = 'C.UTF-8'
  }
  stages {
    stage('build') {
      parallel {
        stage('autotools amd64') {
          agent {
            docker {
              image 'modelicastandardlibrary/build-deps:amd64-20190513'
              label 'linux'
              alwaysPull true
            }
          }
          steps {
            autotools('gcc-4.8')
            autotools('gcc-5')
            autotools('clang-8')
          }
        }
      }
        stage('autotools i386') {
          agent {
            docker {
              image 'modelicastandardlibrary/build-deps:i386-20190513'
              label 'linux'
              alwaysPull true
            }
          }
          steps {
            autotools('gcc-4.8')
            autotools('gcc-5')
            autotools('clang-8')
          }
        }
      }
    }
  }
}

def autotools(CC) {
  sh """
  echo $CC
  rm -f Modelica/Resources/Library/*
  cd Modelica/Resources/BuildProjects/autotools
  ./autogen.sh
  ./configure --prefix="\$PWD/../../Library/linux64"
  make --output-sync -j4
  make install
  """
}
